language: node_js
node_js:
    - '10'
cache: yarn
install:
    - yarn --frozen-lockfile
jobs:
    include:
        - stage: Build and test
          script:
              - yarn test
              - yarn lint
              - yarn build
        - stage: npm release
          script: npm run build
          deploy:
              provider: npm
              email: '$NPM_EMAIL'
              api_key: '$NPM_TOKEN'
              on:
                  tags: true
branches:
    only:
        - master
        - /^v[0-9]+.*$/
