language: node_js
node_js:
    - '10'
cache: npm
install:
    - npm install
jobs:
    include:
        - stage: Build and test
          script:
              - npm run lint
              - npm run test
              - npm run build
        - stage: npm release
          script: npm run build
          deploy:
              provider: npm
              email: '$NPM_EMAIL'
              api_key: '$NPM_TOKEN'
              on:
                  tags: true
branches:
    only:
        - master
        - /^v[0-9]+.*$/
